Expose Internal modules (#8)
* Make Control.Monad.Either a public import in JS.Util.

This fixes
  Error: Control.Monad.Error.Either.EitherT not a data type
when compiling JS.Callback.

Stefan Höck's idea.

* Add internal modules to package, since they get re-exported by public modules.

@benjaminflin's idea; this fixes
https://github.com/stefan-hoeck/idris2-dom/issues/6